name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        process-version:
          - "5"
          - "6"
          - "7"
        exclude:
          - php-version: 7.3
            process-version: 7
          - php-version: 7.4
            process-version: 7
          - php-version: 7.3
            process-version: 6
          - php-version: 7.4
            process-version: 6
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer latest version
        run: |
          composer --version
          composer self-update --2
          composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies with correct symfony process version
        run:  |
          composer require symfony/process:^${{ matrix.process-version }}.0
          git checkout .
          composer update not-installed/here

      - name: Run tests
        run: composer test

      - name: run phpstan
        run: ./vendor/bin/phpstan analyze src tests
